-- MySQL Script generated by MySQL Workbench
-- Tue Aug  6 13:08:55 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema jpaProyecto
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema jpaProyecto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jpaProyecto` DEFAULT CHARACTER SET utf8 ;
USE `jpaProyecto` ;

-- -----------------------------------------------------
-- Table `jpaProyecto`.`paises`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jpaProyecto`.`paises` (
  `p_id` INT NOT NULL AUTO_INCREMENT,
  `p_nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`p_id`),
  UNIQUE INDEX `p_nombre_UNIQUE` (`p_nombre` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jpaProyecto`.`ciudades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jpaProyecto`.`ciudades` (
  `c_id` INT NOT NULL AUTO_INCREMENT,
  `c_nombre` VARCHAR(45) NOT NULL,
  `c_habitantes` INT NOT NULL,
  `p_id` INT NOT NULL,
  PRIMARY KEY (`c_id`),
  INDEX `fk_ciudades_paises_idx` (`p_id` ASC),
  CONSTRAINT `fk_ciudades_paises`
    FOREIGN KEY (`p_id`)
    REFERENCES `jpaProyecto`.`paises` (`p_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
