/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import conexionSQL.conexionSQL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USUARIO PRINCIPAL
 */
public class sistema extends javax.swing.JFrame {
    
    conexionSQL cc=new conexionSQL();
    Connection con=cc.conexion();
    
    

    
    public sistema() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(getBackground());
        mostrarDatos();
        
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtAlbum = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDiscografica = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbDiscjockey = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtValoracion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbEstilo = new javax.swing.JComboBox<>();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablamegamixes = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));

        jLabel1.setText("Álbum");

        jLabel2.setText("Discográfica");

        jLabel3.setText("Discjockey");

        cbDiscjockey.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mike Platinas", "Rául Orellana", "Toni Peret", "Fernando Tijeras" }));

        jLabel4.setText("Valoración");

        jLabel5.setText("Estilo");

        cbEstilo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Italo", "Dance" }));

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtAlbum)
                            .addComponent(txtDiscografica)
                            .addComponent(cbDiscjockey, 0, 194, Short.MAX_VALUE)
                            .addComponent(txtValoracion)
                            .addComponent(cbEstilo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnNuevo)
                        .addGap(2, 2, 2)
                        .addComponent(btnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnActualizar)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDiscografica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbDiscjockey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtValoracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbEstilo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo)
                    .addComponent(btnGuardar)
                    .addComponent(btnEliminar)
                    .addComponent(btnActualizar))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        tablamegamixes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablamegamixes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablamegamixesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablamegamixes);

        jLabel6.setText("Búsqueda:");

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel6)
                        .addGap(29, 29, 29)
                        .addComponent(txtBuscar)))
                .addGap(0, 116, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        
        insertarDatos();
        limpiarCajas();
        mostrarDatos();
        
        
    }
    
     
    
      public void filtrarDatos(String valor) {
        
        String [] titulos={"ID", "Album", "Discografica", "Discjockey", "Valoracion", "Estilo"};
        String [] registros=new String[7];
        
        DefaultTableModel modelo=new DefaultTableModel(null,titulos);
        
        String SQL="select * from megamixes where album like '%"+valor+"%'"; 
        
        try {
            
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery(SQL);
            
                    
            
            
          while (rs.next())  {
              
           registros[0]=rs.getString("idmegamixes");
           registros[1]=rs.getString("album");
           registros[2]=rs.getString("discografica");
           registros[3]=rs.getString("discjockey");
           registros[4]=rs.getString("valoracion");
           registros[5]=rs.getString("estilo");
           
           modelo.addRow(registros);
           
              
          }
          
          tablamegamixes.setModel(modelo);
          
          
          
          
        }catch (Exception e) {
            
         JOptionPane.showMessageDialog(null, "Error al Mostrar Datos"+  e.getMessage());
         
        }
        
        
        
    }
    
    public void mostrarDatos() {
        
        String [] titulos={"ID", "Album", "Discografica", "Discjockey", "Valoracion", "Estilo"};
        String [] registros=new String[7];
        
        DefaultTableModel modelo=new DefaultTableModel(null,titulos);
        
        String SQL="select * from megamixes"; 
        
        try {
            
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery(SQL);
            
                    
            
            
          while (rs.next())  {
              
           registros[0]=rs.getString("idmegamixes");
           registros[1]=rs.getString("album");
           registros[2]=rs.getString("discografica");
           registros[3]=rs.getString("discjockey");
           registros[4]=rs.getString("valoracion");
           registros[5]=rs.getString("estilo");
           
           modelo.addRow(registros);
           
              
          }
          
          tablamegamixes.setModel(modelo);
          
          
          
          
        }catch (Exception e) {
            
         JOptionPane.showMessageDialog(null, "Error al Mostrar Datos"+  e.getMessage());
         
        }
        
        
        
    }
    
    
        public void limpiarCajas () {
            
            txtAlbum.setText("");
            txtDiscografica.setText("");
            txtValoracion.setText("");
            cbEstilo.setSelectedItem(null);
            cbDiscjockey.setSelectedItem(null);
            
            
            
        
    }//GEN-LAST:event_btnGuardarActionPerformed
public void ActualizarDatos(){
        
        
       
        try {
             
            String SQL=" Update megamixes set album=?,discografica=?,discjockey=?,valoracion=?,estilo=? where idmegamixes=? ";
            
            int filaseleccionada=tablamegamixes.getSelectedRow();
            String dao=(String)tablamegamixes.getValueAt(filaseleccionada, 0);
            
            
            
            PreparedStatement pst=con.prepareStatement (SQL);
            
            pst.setString(1, txtAlbum.getText());
            pst.setString(2, txtDiscografica.getText());
            
            int seleccionado=cbDiscjockey.getSelectedIndex();
            pst.setString(3, cbDiscjockey.getItemAt(seleccionado));
            
            pst.setDouble(4, Double.parseDouble(txtValoracion.getText()));
            
            int seleccionado1=cbEstilo.getSelectedIndex();
            pst.setString(5, cbEstilo.getItemAt(seleccionado1));
            
            pst.setString (6, dao);
            
            pst.execute();
            
            JOptionPane.showMessageDialog(null,"Registro Editado Exitoso");
            
            
            
            
             
            
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error de Edición" + e.getMessage());
            
            
        }
     
        
    }
        
        
        
    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        
        limpiarCajas();
        
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void tablamegamixesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablamegamixesMouseClicked
        
        int filaseleccionada=tablamegamixes.rowAtPoint(evt.getPoint());
        
        txtAlbum.setText(tablamegamixes.getValueAt(filaseleccionada, 1).toString());
        txtDiscografica.setText(tablamegamixes.getValueAt(filaseleccionada, 2).toString());
        cbDiscjockey.setSelectedItem(tablamegamixes.getValueAt(filaseleccionada, 3));
        txtValoracion.setText(tablamegamixes.getValueAt(filaseleccionada, 4).toString());
        cbEstilo.setSelectedItem(tablamegamixes.getValueAt(filaseleccionada, 5));
        
        
        
        
        
    }//GEN-LAST:event_tablamegamixesMouseClicked

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
     
        ActualizarDatos();
        limpiarCajas();
        mostrarDatos();
        
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
       
        eliminarRegistros();
        mostrarDatos();
        limpiarCajas();
        
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        filtrarDatos(txtBuscar.getText());
        
    }//GEN-LAST:event_txtBuscarKeyReleased

    public void eliminarRegistros (){
        
        
        int filaseleccionada=tablamegamixes.getSelectedRow();
        
        try {
            String SQL="delete from megamixes where idmegamixes="+tablamegamixes.getValueAt(filaseleccionada, 0);
            
            Statement st=con.createStatement();
            
            int n=st.executeUpdate(SQL);
            
            if (n>=0) {
                
                JOptionPane.showMessageDialog(null, "Registro Eliminado");
                
                
                
            }
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al Eliminar Registros"+ e.getMessage());
            
        }
        
    }
    
    
    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt){
        
        
        
    }
    public void insertarDatos(){
        
        
       
        try {
             
            String SQL="insert into megamixes (album,discografica,discjockey,valoracion,estilo) values (?,?,?,?,?)";
            
            PreparedStatement pst=con.prepareStatement (SQL);
            
            pst.setString(1, txtAlbum.getText());
            pst.setString(2, txtDiscografica.getText());
            
            int seleccionado=cbDiscjockey.getSelectedIndex();
            pst.setString(3, cbDiscjockey.getItemAt(seleccionado));
            
            pst.setDouble(4, Double.parseDouble(txtValoracion.getText()));
            
            int seleccionado1=cbEstilo.getSelectedIndex();
            pst.setString(5, cbEstilo.getItemAt(seleccionado1));
            
            pst.execute();
            
            JOptionPane.showMessageDialog(null,"Registro Exitoso");
            
            
            
            
             
            
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error de Registro" + e.getMessage());
            
            
        }
     
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sistema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox<String> cbDiscjockey;
    private javax.swing.JComboBox<String> cbEstilo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablamegamixes;
    private javax.swing.JTextField txtAlbum;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtDiscografica;
    private javax.swing.JTextField txtValoracion;
    // End of variables declaration//GEN-END:variables
}
